services:
  - type: web
    name: meen-backend
    env: node
    buildCommand: npm install
    startCommand: npm run prod-server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true